### ISSUE TITLE
Is it work with High Sierra 10.13.6?

### ISSUE THREAD

**Issue by abhisit** [Slbomber/AsusH81MK-macos#1]
Since, I could not find/download High Sierra 10.13.4 on Apple Store, so I raised this issue up.
Thank you for your beautiful work.

**Comment by Slbomber** [comment]
I'm update repo to 10.13.6 today. Just wait few hours

**Comment by abhisit** [comment]
Thank you so much!

**Comment by Slbomber** [comment]
Please test this configuration

**Comment by abhisit** [comment]
I have the old i7-4770 (Intel® HD Graphics 4600) and I am buying H81M-K (your reply makes me more an easier decision to but it, thank a lot).

SSD + no external GPU and the display is connected to onboard Intel HD 4600 DVI (1920*1080).

I will test and let you know the result.
